# Generated by Django 5.1.2 on 2024-10-15 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
